### PR TITLE
Fix illegal instructions failures in examples

### PR DESCRIPTION
**Pull request by Vika-F**
The implementations of the methods that could potentially be the cause of illegal instructions issues in the examples are moved away from header files.

---

PR should start as a draft, then move to ready for review state after CI is passed and all applicable checkboxes are closed.
This approach ensures that reviewers don't spend extra time asking for regular requirements.

You can remove a checkbox as not applicable only if it doesn't relate to this PR in any way.
For example, PR with docs update doesn't require checkboxes for performance while PR with any change in actual code should have checkboxes and justify how this code change is expected to affect performance (or justification should be self-evident).

Checklist to comply with **before moving PR from draft**:

**PR completeness and readability**

- [x] I have reviewed my changes thoroughly before submitting this pull request.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/uxlfoundation/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [x] I have added a respective label(s) to PR if I have a permission for that.
- [x] I have resolved any merge conflicts that might occur with the base branch.

**Testing**

- [x] I have run it locally and tested the changes extensively.
- [x] All CI jobs are green or I have provided justification why they aren't.

### CODE REVIEW

**Comment by david-cortes-intel** [comment]
Looks like it wasn't enough to fix the problem unfortunately:
```
16:52:48 FAILED		svm_two_class_thunder_csr_batch with errno 132
.ci/scripts/test.sh: line 248: 46928 Illegal instruction     (core dumped) ${run_command} > "${e}".res 2>&1
```

There's a few more PRs I merged with the same pattern of using `= delete` in header files:
https://github.com/uxlfoundation/oneDAL/pull/2998/files
https://github.com/uxlfoundation/oneDAL/pull/2997/files
https://github.com/uxlfoundation/oneDAL/pull/2996/files

Plus this one which defines a constructor in a header - not sure if relevant as it was there before already:
https://github.com/uxlfoundation/oneDAL/pull/2994/files

And this one which added `= default` in headers:
https://github.com/uxlfoundation/oneDAL/pull/3006/files

I think a valgrind job would be really helpful here to validate that these are actually the culprits.

**Comment by Vika-F** [comment]
@david-cortes-intel yes, but #2996, #2997, #2998 are in `cpp/oneapi/dal`, which should not have those problems. Only `cpp/daal` build sub-system is fragile in terms of illegal instructions.
The fix for the cases from #3006 is also included into this PR.

I will dig further - planning to reproduce locally.

**Comment by david-cortes-intel** [comment]
In case it helps, the breakage seems to have started with this commit:
https://github.com/uxlfoundation/oneDAL/pull/2991

This PR has CI jobs with reproducers - succeds before that PR, fails after adding it:
https://github.com/uxlfoundation/oneDAL/pull/3014

**Comment by Vika-F** [comment]
> In case it helps, the breakage seems to have started with this commit: #2991
> 
> This PR has CI jobs with reproducers - succeds before that PR, fails after adding it: #3014

@david-cortes-intel Yes, that helps very much. Thank you! Didn't understood that during the call.

**Review by david-cortes-intel — APPROVED** [review]
Perhaps these patterns could be added as coding guidelines for implementation of algorithms in the docs.

**Pull request merged**
